-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["x"] = 0,0,
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                },
                ["sizepolicy"] = "full",
                ["level"] = 0,0,
                ["type"] = "WGroupWS",
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,0,
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 1,0,
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 12583076,0,
                                                    ["geom"] = {
                                                        ["x"] = 0,0,
                                                        ["w"] = 1364,0,
                                                        ["h"] = 736,0,
                                                        ["y"] = 0,0,
                                                    },
                                                    ["level"] = 1,0,
                                                },
                                            },
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["x"] = 1,0,
                                                ["w"] = 1364,0,
                                                ["h"] = 736,0,
                                                ["y"] = 16,0,
                                            },
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0,0,
                                            ["hidden"] = true,
                                            ["name"] = "WGroupCW",
                                        },
                                        [2] = {
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["x"] = 1,0,
                                                ["w"] = 1364,0,
                                                ["h"] = 736,0,
                                                ["y"] = 16,0,
                                            },
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0,0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 2,0,
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 16777225,0,
                                                    ["geom"] = {
                                                        ["x"] = 1,0,
                                                        ["w"] = 1362,0,
                                                        ["h"] = 736,0,
                                                        ["y"] = 0,0,
                                                    },
                                                    ["level"] = 1,0,
                                                },
                                            },
                                            ["name"] = "WGroupCW<2>",
                                        },
                                    },
                                    ["name"] = "Tiling Frame<3>",
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["brs"] = 15,0,
                            ["tls"] = 753,0,
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["x"] = 0,0,
                            ["w"] = 1366,0,
                            ["h"] = 768,0,
                            ["y"] = 0,0,
                        },
                        ["level"] = 0,0,
                        ["name"] = "WTiling",
                    },
                },
                ["name"] = "WGroupWS",
            },
            [2] = {
                ["pseudomodal"] = true,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["level"] = 1,0,
                ["initial_outputs"] = {
                },
                ["geom"] = {
                    ["x"] = 0,0,
                    ["w"] = 1366,0,
                    ["h"] = 768,0,
                    ["y"] = 0,0,
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 363,0,
                            ["w"] = 636,0,
                            ["h"] = 478,0,
                            ["y"] = 144,0,
                        },
                        ["sizepolicy"] = "free_glue",
                        ["level"] = 1025,0,
                        ["mode"] = 0,0,
                        ["type"] = "WFrame",
                        ["managed"] = {
                            [1] = {
                                ["switchto"] = true,
                                ["sizepolicy"] = "full",
                                ["geom"] = {
                                    ["x"] = 1,0,
                                    ["w"] = 634,0,
                                    ["h"] = 460,0,
                                    ["y"] = 16,0,
                                },
                                ["type"] = "WGroupCW",
                                ["level"] = 0,0,
                                ["managed"] = {
                                    [1] = {
                                        ["checkcode"] = 3,0,
                                        ["sizepolicy"] = "full",
                                        ["bottom"] = true,
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 14680073,0,
                                        ["geom"] = {
                                            ["x"] = 0,0,
                                            ["w"] = 634,0,
                                            ["h"] = 460,0,
                                            ["y"] = 0,0,
                                        },
                                        ["level"] = 1,0,
                                    },
                                },
                                ["name"] = "WGroupCW<1>",
                            },
                        },
                        ["name"] = "*scratchpad*",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
            },
        },
        ["name"] = "WScreen",
    },
}

